# Generated by Django 4.0.2 on 2022-04-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='category',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='crime',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='lat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='crime',
            name='long',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='crime',
            name='nom',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
